### ISSUE TITLE
Democratic-csi container is not versioned

### ISSUE THREAD

**Issue by kennyiv** [democratic-csi/charts#23]
Within the chart all of the images except for democratic-csi use an explicitly defined version. Is that an intentional design decision? I was running a version of the democratic-csi chart from a year ago. Nodes that pulled democratic-csi:latest from that time still work but newer nodes have ran into an issue: csi-driver - ""BREAKING CHANGE since v1.5.3! datasetPermissionsUser must be numeric: root is invalid"". Is the expectation here that regular updates should be made or should the democratic-csi image use tagged versions?

**Comment by travisghansen** [comment]
It's intentional that I left the defaults at `latest`. I think that's the only backwards-incompatible change that's been introduced in the lifetime of the project. However, in production setups I would pin the versions and plan on updating at a regular cadence.

Aside from that change you should also be aware of this: https://github.com/democratic-csi/democratic-csi/issues/164 the title says `Nomad` but in certain cases it can impact `k8s` as well. The TLDR; is use the latest chart version when deploying `democratic-csi` version `v1.6.0` +

**Comment by kennyiv** [comment]
Awesome thanks, I appreciate the response.
